drop table product_tbl;
drop table reply_tbl;
drop table user_tbl;
drop table board_tbl;
drop SEQUENCE seq_board;


CREATE TABLE BOARD_TBL 
(
  BNO NUMBER(10, 0) NOT NULL 
, TITLE VARCHAR2(200 BYTE) NOT NULL 
, CONTENT VARCHAR2(200 BYTE) NOT NULL 
, WRITER VARCHAR2(50 BYTE) NOT NULL 
, REGDATE DATE DEFAULT sysdate 
, UPDATEDATE DATE DEFAULT sysdate 
, CONSTRAINT BOARD_TBL_PK PRIMARY KEY 
  (
    BNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BOARD_TBL_PK ON BOARD_TBL (BNO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE USER_TBL 
(
  ID VARCHAR2(8 BYTE) NOT NULL 
, PASSWORD VARCHAR2(8 BYTE) 
, NAME VARCHAR2(20 BYTE) 
, ROLE VARCHAR2(5 BYTE) 
, CONSTRAINT USER_TBL_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USER_TBL_PK ON USER_TBL (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;


CREATE TABLE PRODUCT_TBL 
(
  PRONAME VARCHAR2(20) NOT NULL 
, AMOUNT NUMBER 
, PRICE NUMBER 
, IMGSRC VARCHAR2(30) 
, CONTENT VARCHAR2(150) 
, CONSTRAINT PRODUCT_TBL_PK PRIMARY KEY 
  (
    PRONAME 
  )
  ENABLE 
);

CREATE TABLE REPLY_TBL 
(
  RNO NUMBER(10, 0) NOT NULL 
, BNO NUMBER(10, 0) NOT NULL 
, REPLY VARCHAR2(1000 BYTE) NOT NULL 
, REPLYER VARCHAR2(50 BYTE) NOT NULL 
, REPLYDATE DATE DEFAULT sysdate 
, UPDATEDATE DATE DEFAULT sysdate 
, CONSTRAINT PK_REPLY PRIMARY KEY 
  (
    RNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_REPLY ON REPLY_TBL (RNO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE REPLY_TBL
ADD CONSTRAINT FK_REPLY_BOARD FOREIGN KEY
(
  BNO 
)
REFERENCES BOARD_TBL
(
  BNO 
)
ENABLE;



CREATE SEQUENCE seq_board START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;

ALTER TABLE USER_TBL  
MODIFY (ROLE DEFAULT 'user' );

ALTER TABLE PRODUCT_TBL  
MODIFY (AMOUNT DEFAULT 0 );


