drop table product_tbl;

drop table board_tbl;

drop table reply_tbl;
drop table user_tbl;
drop SEQUENCE seq_board;

CREATE TABLE USER_TBL 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) 
, NAME VARCHAR2(20 BYTE) 
, ROLE VARCHAR2(20 BYTE) 
, CONSTRAINT USER_TBL_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USER_TBL_PK ON USER_TBL (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;



CREATE TABLE PRODUCT_TBL 
(
  PRONAME VARCHAR2(20) NOT NULL 
, AMOUNT NUMBER 
, PRICE NUMBER 
, IMGSRC VARCHAR2(30) 
, CONTENT VARCHAR2(150) 
, CONSTRAINT PRODUCT_TBL_PK PRIMARY KEY 
  (
    PRONAME 
  )
  ENABLE 
);

CREATE TABLE REPLY_TBL 
(
  RNO NUMBER(10, 0) NOT NULL 
, CONTENT VARCHAR2(150 BYTE) 
, WRITER VARCHAR2(20 BYTE) NOT NULL 
, DAYDATE DATE 
, CONSTRAINT REPLY_TBL_PK PRIMARY KEY 
  (
    WRITER 
  , RNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX REPLY_TBL_PK ON REPLY_TBL (WRITER ASC, RNO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE REPLY_TBL
ADD CONSTRAINT REPLY_TBL_FK1 FOREIGN KEY
(
  WRITER 
)
REFERENCES USER_TBL
(
  ID 
)
ENABLE;


CREATE TABLE BOARD_TBL 
(
  TITLE VARCHAR2(20 BYTE) NOT NULL 
, WRITER VARCHAR2(20 BYTE) NOT NULL 
, CONTENT VARCHAR2(150 BYTE) 
, REGDATE DATE 
, CNT NUMBER 
, BNO NUMBER NOT NULL 
, CONSTRAINT BOARD_TBL_PK PRIMARY KEY 
  (
    WRITER 
  , BNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BOARD_TBL_PK ON BOARD_TBL (WRITER ASC, BNO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE BOARD_TBL
ADD CONSTRAINT BOARD_TBL_FK1 FOREIGN KEY
(
  WRITER 
)
REFERENCES USER_TBL
(
  ID 
)
ENABLE;

ALTER TABLE BOARD_TBL
ADD CONSTRAINT BOARD_TBL_FK2 FOREIGN KEY
(
  WRITER 
, BNO 
)
REFERENCES REPLY_TBL
(
  WRITER 
, RNO 
)
ENABLE;




CREATE SEQUENCE seq_board START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;

ALTER TABLE USER_TBL  
MODIFY (ROLE DEFAULT 'user' );

ALTER TABLE PRODUCT_TBL  
MODIFY (AMOUNT DEFAULT 0 );


