-- USER SQL
CREATE USER BEAUTIFUL IDENTIFIED BY 1234  
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- QUOTAS

-- ROLES
GRANT DBA TO BEAUTIFUL ;
GRANT CONNECT TO BEAUTIFUL ;
GRANT RESOURCE TO BEAUTIFUL ;

-- SYSTEM PRIVILEGES

